export default {
  nav: {
    home: 'Home', solutions: 'Solutions', ai: 'Shoply AI', platform: 'Platform', deployment: 'Deployment', signIn: 'Sign in', signUp: 'Start free', language: 'Language', menu: 'Open menu', closeMenu: 'Close menu',
  },
  footer: {
    description: 'AI-powered commerce infrastructure for global brands, independent sellers and growing teams.',
    product: 'Product', resources: 'Resources', company: 'Company', home: 'Home', solutions: 'Solutions', ai: 'Shoply AI', platform: 'Platform', openPlatform: 'Open platform', privacy: 'Privacy policy', terms: 'Terms of service', admin: 'Admin', copyright: 'Shoply. All rights reserved.', operator: 'Operated by Fastix Limited. Technical support by Shenzhen Kuaiqin Technology Co., Ltd.',
  },
  seo: {
    title: 'Shoply AI E-commerce Solution',
    description: 'Build a growth-focused global storefront with AI marketing, SEO, flexible applications and private deployment options.',
  },
  hero: {
    eyebrow: 'AI-powered commerce infrastructure',
    titleBefore: 'Build a global store', titleAccent: 'focused on growth',
    description: 'Launch and operate a conversion-focused independent storefront with flexible themes, extensible apps, AI-assisted content and global commerce capabilities.',
    primary: 'Start free', secondary: 'Explore solutions', proof: 'Built for independent commerce',
    visualUrl: 'shoply.store', visualBadge: 'Live storefront', visualTitle: 'Summer collection', visualSubtitle: 'Designed, localized and ready to publish', visualButton: 'Shop now', visualProduct: 'New arrival', visualDiscount: 'Growth',
  },
  values: {
    label: 'Why Shoply', title: 'Own the customer journey, from first visit to fulfillment', description: 'A commerce foundation designed to give growing teams more control over brand, data and operations.',
    items: [
      { icon: 'ph:magic-wand-duotone', title: 'AI SEO + acquisition', description: 'Create and refine content that supports organic discovery and proactive customer acquisition.' },
      { icon: 'ph:chart-line-up-duotone', title: 'Independent growth', description: 'Build your own brand storefront without marketplace commission on every order.' },
      { icon: 'ph:shield-check-duotone', title: 'Private deployment', description: 'Choose an independently deployed environment when data control and customization matter.' },
      { icon: 'ph:credit-card-duotone', title: 'Flexible payments', description: 'Connect payment methods that fit your market, including mainstream online and local options.' },
    ],
  },
  audiences: {
    label: 'Built for real commerce', title: 'One platform, multiple growth paths', description: 'Start from your current business model and extend as your operation matures.', action: 'See what fits',
    items: [
      { icon: 'ph:rocket-launch-duotone', title: 'New sellers', description: 'Launch with guided setup, flexible sections and a clear operational path.', tags: ['Guided setup', 'Theme sections', 'Business insights'] },
      { icon: 'ph:storefront-duotone', title: 'Marketplace sellers', description: 'Add an owned channel for customer retention and long-term brand value.', tags: ['Product migration', 'Customer ownership', 'Multi-channel'] },
      { icon: 'ph:buildings-duotone', title: 'B2B and wholesale', description: 'Present your company and products with workflows suited to larger inquiries.', tags: ['Brand website', 'Product catalog', 'Lead conversion'] },
      { icon: 'ph:code-duotone', title: 'Independent deployment', description: 'Gain a customizable commerce stack with applications and open integration points.', tags: ['Extensible apps', 'Private runtime', 'API integration'] },
    ],
  },
  ai: {
    label: 'Shoply AI', title: 'An intelligent partner inside your commerce workflow', description: 'Use AI where it supports the work: improve product content, polish articles, identify opportunities and turn operational questions into clearer insights.', action: 'Book a demo', panelTitle: 'Product title assistant', panelHint: 'Five market-ready directions based on product context',
    items: [
      { icon: 'ph:text-aa-duotone', title: 'Product title optimization', description: 'Refine product titles around attributes, intent and selling context.' },
      { icon: 'ph:article-duotone', title: 'Blog polishing', description: 'Improve structure, clarity and grammar for more useful commerce content.' },
      { icon: 'ph:envelope-simple-open-duotone', title: 'Order recall', description: 'Support targeted follow-up for unpaid orders based on operational signals.' },
      { icon: 'ph:magnifying-glass-duotone', title: 'Data discovery', description: 'Ask business questions naturally and surface relevant operational information.' },
    ],
  },
  platform: {
    label: 'Integrated commerce platform', title: 'The capabilities to launch, operate and grow', description: 'Keep the customer-facing store and operational workflows connected without stitching together a different tool for every step.',
    items: [
      { icon: 'ph:paint-brush-broad-duotone', title: 'Storefront building', description: 'Flexible themes and sections for B2C, B2B and international brand websites.' },
      { icon: 'ph:arrows-left-right-duotone', title: 'Product migration', description: 'Bring products from established domestic and international sales channels.' },
      { icon: 'ph:puzzle-piece-duotone', title: 'Application ecosystem', description: 'Extend the platform with applications that address different business scenarios.' },
      { icon: 'ph:cube-duotone', title: 'Product operations', description: 'Manage multiple stores, products, variants and inventory from a unified workspace.' },
      { icon: 'ph:package-duotone', title: 'Order fulfillment', description: 'Support the flow from order creation and payment through shipping and after-sales.' },
      { icon: 'ph:globe-hemisphere-west-duotone', title: 'Localized commerce', description: 'Serve international markets with language, currency and payment flexibility.' },
      { icon: 'ph:megaphone-duotone', title: 'Traffic acquisition', description: 'Connect content, SEO and campaign operations around measurable growth.' },
      { icon: 'ph:gauge-duotone', title: 'Data cockpit', description: 'Use operational reporting to understand sales and make clearer decisions.' },
    ],
  },
  ecosystem: {
    label: 'Connected by design', title: 'Work with the channels and tools your business needs', description: 'Shoply brings storefront, payments, marketing and communications into one extensible commerce foundation.',
    items: ['PayPal', 'Stripe', 'Shopify', 'Amazon', 'Google Ads', 'Facebook', 'WhatsApp', 'COD'],
  },
  deployment: {
    label: 'Flexible deployment', title: 'Choose the operating model that fits', description: 'Start quickly with SaaS or choose private deployment when customization and infrastructure control are essential.',
    items: [
      { icon: 'ph:cloud-check-duotone', badge: 'Fast start', title: 'SaaS cloud service', description: 'Use a managed Shoply environment with flexible subscription options and a lower operational burden.', action: 'Start free' },
      { icon: 'ph:hard-drives-duotone', badge: 'More control', title: 'Private deployment', description: 'Deploy with a containerized architecture for deeper customization, scaling and data control.', action: 'Talk to us' },
    ],
  },
  cta: { eyebrow: 'Ready to build your owned channel?', title: 'Turn your next market opportunity into a storefront', description: 'Start with Shoply today, or talk with our team about a tailored commerce deployment.', primary: 'Start free', secondary: 'Book a consultation' },
  pages: {
    marketing: {
      about: {
        eyebrow: 'About Shoply', title: 'Digital productivity for global commerce teams', description: 'Founded in 2015, Shenzhen Kuaiqin Technology Co., Ltd. builds self-developed software that makes cross-border commerce easier to launch and operate.', primary: 'Start free', secondary: 'Contact us', icon: 'ph:buildings-duotone', highlights: ['Founded in 2015', 'Technology-led', 'AI-assisted operations', 'Global commerce'], sectionLabel: 'Our direction', sectionTitle: 'Use technology to drive business', sectionDescription: 'Shoply combines approachable software with an extensible commerce foundation for sellers and suppliers.', sections: [{ title: 'Our mission', description: 'Build a simple yet advanced platform that helps merchants streamline online business and improve operating efficiency.' }, { title: 'AI efficiency', description: 'Integrate AI into content, outreach and customer service workflows to reduce repetitive work.' }, { title: 'Proactive acquisition', description: 'Support teams in finding and approaching relevant customer groups with clearer operating tools.' }], note: 'Our business covers software development, technical services, consulting, artificial intelligence application software and internet commerce services.', ctaTitle: 'Build the next stage of your commerce business', ctaDescription: 'Talk with the Shoply team about SaaS or an independently deployed solution.', seoTitle: 'About Shoply', seoDescription: 'Learn about Shoply and Shenzhen Kuaiqin Technology Co., Ltd., founded to make cross-border commerce easier.'
      },
      'amazon-store': {
        eyebrow: 'Amazon seller solution', title: 'Turn marketplace traffic into a channel you own', description: 'Create a focused marketing storefront for Amazon products and open a new path for customer acquisition and brand growth.', primary: 'Start free', secondary: 'Book a demo', icon: 'ph:amazon-logo-duotone', highlights: ['Traffic acquisition', 'Social channels', 'Data insights', 'Marketing operations'], sectionLabel: 'Beyond the marketplace', sectionTitle: 'A marketing site built around Amazon sellers', sectionDescription: 'Give campaigns, content and customer relationships a destination outside the marketplace listing.', sections: [{ title: 'Bring traffic together', description: 'Use a branded destination for advertising, social content and product discovery.' }, { title: 'Present the brand', description: 'Explain product value, positioning and stories beyond marketplace listing constraints.' }, { title: 'Measure engagement', description: 'Connect marketing activity with clearer storefront and customer signals.' }], note: '', ctaTitle: 'Open a new growth path for your Amazon business', ctaDescription: 'Start with Shoply or discuss the right marketing-store structure with us.', seoTitle: 'Amazon Marketing Storefront | Shoply', seoDescription: 'Build an independent marketing storefront for Amazon traffic, brand content and customer acquisition.'
      },
      'b2b-website': {
        eyebrow: 'B2B commerce', title: 'A B2B website designed to generate real inquiries', description: 'Launch a ready-to-use international business website that presents products clearly and helps sales teams capture qualified leads.', primary: 'Start free', secondary: 'Book a demo', icon: 'ph:handshake-duotone', highlights: ['Inquiry conversion', 'Product catalog', 'Brand credibility', 'SaaS stability'], sectionLabel: 'Built for B2B', sectionTitle: 'Move from company profile to commercial conversation', sectionDescription: 'Structure company, product and contact information around the needs of international buyers.', sections: [{ title: 'Professional presence', description: 'Create a credible multilingual company website with a consistent brand experience.' }, { title: 'Product-led discovery', description: 'Organize catalogs and product details so buyers can evaluate your offering quickly.' }, { title: 'Inquiry workflow', description: 'Guide prospective customers toward clear contact and consultation actions.' }], note: '', ctaTitle: 'Build a B2B website that supports your sales team', ctaDescription: 'Launch quickly with SaaS or discuss a tailored deployment.', seoTitle: 'B2B Brand Website Solution | Shoply', seoDescription: 'Build a professional B2B website with product catalogs, multilingual content and inquiry conversion.'
      },
      'b2c-store': {
        eyebrow: 'B2C independent store', title: 'Build a global store without marketplace lock-in', description: 'Create a brand-led B2C storefront with SEO support, localized currencies and flexible payment methods.', primary: 'Start free', secondary: 'Book a demo', icon: 'ph:storefront-duotone', highlights: ['Owned storefront', 'SEO foundation', 'Multi-currency', 'Flexible payments'], sectionLabel: 'Own the experience', sectionTitle: 'Everything a growing B2C brand needs to launch', sectionDescription: 'Connect product presentation, localized buying and day-to-day commerce operations.', sections: [{ title: 'Brand-first design', description: 'Use flexible themes and sections to express a distinctive customer-facing identity.' }, { title: 'Global checkout', description: 'Serve different markets with language, currency and payment flexibility.' }, { title: 'Operational control', description: 'Manage products and orders without depending on a single marketplace account.' }], note: '', ctaTitle: 'Launch the store your brand deserves', ctaDescription: 'Start building today and keep control of your customer relationship.', seoTitle: 'B2C Independent Store Solution | Shoply', seoDescription: 'Build a global B2C storefront with SEO, localized currencies, payments and independent brand control.'
      },
      case: {
        eyebrow: 'Shoply projects', title: 'Commerce systems shaped around real business needs', description: 'Shoply supports B2C stores, B2B brand websites, Amazon marketing sites and tailored commerce delivery.', primary: 'Start free', secondary: 'Discuss a project', icon: 'ph:briefcase-duotone', highlights: ['B2C stores', 'B2B websites', 'Amazon marketing', 'Custom delivery'], sectionLabel: 'Project directions', sectionTitle: 'Choose the delivery path that matches your business', sectionDescription: 'The current public site does not publish named customer case details; contact us for relevant project references.', sections: [{ title: 'Independent stores', description: 'Brand storefronts and commerce operations for direct-to-consumer businesses.' }, { title: 'International B2B', description: 'Company, catalog and inquiry experiences for global trade teams.' }, { title: 'Tailored systems', description: 'Deeper customization when standard SaaS workflows do not fit the project.' }], note: 'To protect customer information, project names and private implementation details are not fabricated or disclosed on this page.', ctaTitle: 'Tell us what you need to build', ctaDescription: 'We will help identify whether SaaS, private deployment or a tailored project fits best.', seoTitle: 'Shoply Commerce Project Cases', seoDescription: 'Explore Shoply delivery directions for B2C, B2B, Amazon marketing and custom commerce projects.'
      },
      custom: {
        eyebrow: 'Custom development', title: 'Where design and technology become your unique website', description: 'Extend Shoply when your business needs specialized storefront experiences, workflows or integrations.', primary: 'Start a project', secondary: 'Book a consultation', icon: 'ph:code-duotone', highlights: ['Business discovery', 'Experience design', 'Custom development', 'Delivery support'], sectionLabel: 'A clear delivery path', sectionTitle: 'From requirements to a maintainable commerce system', sectionDescription: 'Keep custom work grounded in real business goals and an extensible technical foundation.', sections: [{ title: 'Discover', description: 'Clarify the business scenario, users, required integrations and success criteria.' }, { title: 'Design and build', description: 'Create the customer experience and implement the agreed storefront and workflows.' }, { title: 'Deliver and evolve', description: 'Verify the result, hand over the system and plan future improvements.' }], note: 'Custom scope, delivery dates and pricing are confirmed after requirements review.', ctaTitle: 'Bring your commerce idea to life', ctaDescription: 'Share the business context and the Shoply team will help shape the delivery plan.', seoTitle: 'Shoply Custom Commerce Development', seoDescription: 'Custom storefront, workflow and integration development built on the Shoply commerce foundation.'
      },
      install: {
        eyebrow: 'Independent deployment', title: 'Install Shoply on your own server', description: 'Run Shoply on a Linux or macOS server through a guided installation or a manually managed package.', primary: 'Get started', secondary: 'Deployment support', icon: 'ph:terminal-window-duotone', highlights: ['Linux and macOS', 'Multiple architectures', 'Guided install', 'Manual deployment'], sectionLabel: 'Installation path', sectionTitle: 'Prepare, install and verify', sectionDescription: 'Independent deployment requires basic server administration and a supported environment.', sections: [{ title: 'Prepare a server', description: 'Use a mainstream Linux distribution or macOS environment.', items: ['CentOS, Ubuntu and Debian families', 'x86_64, aarch64, armv7l, ppc64le and s390x'] }, { title: 'Run the installer', description: 'Use an administrator account to download and install the Shoply runtime.' }, { title: 'Manual deployment', description: 'Choose a platform package when you need to manage installation and operations yourself.', items: ['Linux amd64', 'Windows amd64', 'macOS amd64'] }], note: 'Verify the current package, license and production requirements with the Shoply team before deployment. This page does not expose an unverified shell command.', ctaTitle: 'Need help with independent deployment?', ctaDescription: 'Discuss infrastructure, architecture and operational requirements with us first.', seoTitle: 'Install Shoply Online', seoDescription: 'Review Shoply independent deployment requirements for Linux, macOS and supported server architectures.'
      },
      migration: {
        eyebrow: 'Store migration', title: 'Migrate your store without losing the path to growth', description: 'Already use Shopify, Shopline or a WeChat store? Add a Shoply independent site to reach more markets.', primary: 'Start free', secondary: 'Book a demo', icon: 'ph:arrows-left-right-duotone', highlights: ['No-code operation', 'Lower labor cost', 'Traffic continuity', 'Store data migration'], sectionLabel: 'Fast migration', sectionTitle: 'Move store data with a clearer operating path', sectionDescription: 'Reduce repetitive setup and prepare your products and operations for an owned storefront.', sections: [{ title: 'Connect the source', description: 'Confirm the existing storefront and the data that should be migrated.' }, { title: 'Move store data', description: 'Transfer supported product and store information into the new environment.' }, { title: 'Verify and launch', description: 'Review migrated data and prepare the new independent site for operation.' }], note: 'Migration coverage depends on the source platform and available data. Confirm supported fields before production migration.', ctaTitle: 'Expand into your next market with Shoply', ctaDescription: 'Start free or talk with us about your current store migration.', seoTitle: 'Store Migration Solution | Shoply', seoDescription: 'Migrate supported store data to Shoply and launch an independent storefront without code-heavy setup.'
      },
      weidian: {
        eyebrow: 'Weidian migration', title: 'Move your Weidian store to an independent storefront', description: 'Connect your existing store, synchronize supported commerce data and start operating a channel you control.', primary: 'Start free trial', secondary: 'Migration support', icon: 'ph:shopping-bag-open-duotone', highlights: ['14-day trial', 'Multi-store management', 'Product sync', 'Order sync'], sectionLabel: 'One-click migration', sectionTitle: 'A straightforward path from Weidian to Shoply', sectionDescription: 'Reduce manual setup and bring the core store workflow into an independent environment.', sections: [{ title: 'Add the store address', description: 'Manage multiple stores and securely connect the supported source data.' }, { title: 'Synchronize products and orders', description: 'Fetch supported product, order and customer information into the migration workflow.' }, { title: 'Launch the independent site', description: 'Review the new store and begin operating your owned channel.' }], note: 'The online site states a 14-day free trial. Actual trial eligibility follows the current APay subscription product configuration.', ctaTitle: 'Ready to own your independent brand?', ctaDescription: 'Start your Shoply journey and keep your business in your own hands.', seoTitle: 'Weidian Store Migration | Shoply', seoDescription: 'Migrate supported Weidian products and orders to a Shoply independent storefront.'
      }
    },
    legal: {
      cookies: {
        title: 'Cookie Policy', updated: 'Last Updated: 2025-08-05', intro: 'This policy explains what cookies are, how Shoply uses them and the choices available to you.', seoTitle: 'Cookie Policy | Shoply', seoDescription: 'Learn how Shoply uses essential, analytics, personalization and advertising cookies.', sections: [
          { title: 'What are cookies?', paragraphs: ['Cookies are small data files placed on your computer or mobile device when you visit a website. They store information about you and your preferences, such as login state, cart contents or language settings, helping provide a more personalized and efficient browsing experience.'] },
          { title: 'How we use cookies', paragraphs: ['We use essential cookies for website operation and secure areas; performance and analytics cookies to understand pages, time spent and errors; personalization cookies to remember language or region; and advertising cookies that may be used with third-party partners to provide more relevant marketing.'] },
          { title: 'Types of cookies', paragraphs: ['Session cookies exist temporarily while the browser is open. Persistent cookies remain after the browser closes. First-party cookies are set directly by Shoply, while third-party cookies may be set by providers such as Google Analytics and Google Ads.'] },
          { title: 'Your choices', paragraphs: ['Most browsers allow you to control or reject cookies. Disabling some cookies may prevent parts of the website from working normally or providing a personalized experience.'] },
          { title: 'Changes and contact', paragraphs: ['We may update this policy for business, legal or technical changes and will publish the new version on this page. For questions, contact support@shoply.cm.'] }
        ]
      },
      privacy: {
        title: 'Privacy Policy', updated: 'Last Updated: 2024-08-05', intro: 'Your privacy is important to us. We respect your privacy and comply with applicable laws and regulations regarding personal information collected through shoply.run, related services and third-party platforms.', seoTitle: 'Privacy Policy | Shoply', seoDescription: 'Read how Shoply collects, uses, stores, protects and discloses personal information.', sections: [
          { title: 'Information we collect', paragraphs: ['Personal information is information that can identify you. It may be collected automatically when your device accesses our services or voluntarily when you provide it.', 'Automatically collected information may include IP address, device type, operating system, browser, pages visited, date, time, duration and technical error details. Voluntarily provided information may include your name, email address, payment information and public social profile information.'] },
          { title: 'How and why we use information', paragraphs: ['We collect and use personal information only when we have a valid reason: your consent, performance of a contract or transaction, our legitimate interests, or compliance with law.', 'Uses may include providing the website and platform, processing transactions or recurring payments, personalizing your experience, communications, internal records, analytics, research, advertising, legal compliance, dispute resolution, security and fraud prevention.'] },
          { title: 'Data controller and third parties', paragraphs: ['shoply.run is the data controller for personal information you provide. We may disclose information to related entities, service providers, employees, contractors, business partners, courts, regulators, law enforcement, professional advisers and entities involved in a transfer of the business.', 'Current third-party categories include Google analytics and advertising services, Alibaba Cloud hosting and storage, and SendCloud email delivery.'] },
          { title: 'Storage and protection', paragraphs: ['We retain personal information only as long as needed for its purpose or legal, accounting and reporting obligations. We use commercially acceptable safeguards against loss, theft and unauthorized access, but no electronic transmission or storage method is completely secure.'] },
          { title: 'Children and international transfers', paragraphs: ['Our products and services are not directed to children under 13 and we do not knowingly collect their personal information.', 'Collected information is stored in China. Transfers to other countries will be made in accordance with applicable law and protected under this policy.'] },
          { title: 'Your rights', paragraphs: ['Depending on applicable law, you may withdraw consent, request access or correction, object to or restrict processing, request portability or deletion, complain about processing and unsubscribe from marketing. We will not discriminate against you for exercising these rights. Legal exceptions may apply.'] },
          { title: 'Cookies, external links and changes', paragraphs: ['We use cookies to understand use of the website and provide content according to preferences. See the Cookie Policy for details.', 'External websites have their own privacy policies and are outside our control. We may update this policy and will publish changes at this location, requesting consent where required by law.'] },
          { title: 'Contact us', paragraphs: ['For privacy questions or concerns, contact our data protection officer at support@shoply.cm.'] }
        ]
      },
      terms: {
        title: 'Terms of Service', updated: 'Last Updated: 2024-08-05', intro: 'By accessing the services and data on shoply.run, you agree to these Terms of Service and all applicable laws and regulations. If you do not agree, you may not use Shoply services.', seoTitle: 'Terms of Service | Shoply', seoDescription: 'Read the Shoply service terms, license, refund policy, liability and governing law.', sections: [
          { title: 'Service provider', paragraphs: ['The provider and contracting party for shoply.run is Shenzhen Kuaiqin Technology Co., Ltd., established under Chinese law at Room 402, Building 123, Daxikan No. 2 Village, Dahong Community, Xili Street, Nanshan District, Shenzhen.'] },
          { title: 'Use license', paragraphs: ['Shoply provides services to businesses, not individual consumers. You receive a license to use and download permitted materials, not ownership.', 'You may not modify, copy, create derivative works, decompile or reverse engineer materials; remove proprietary notices; mirror materials without added value; remove Shoply copyright information without a commercial license; or misrepresent ownership or source. The license terminates if these restrictions are violated.'] },
          { title: 'Refund policy', paragraphs: ['Shoply offers a full refund when the request is submitted within 7 business days from the first payment or contract signing, subject to the applicable agreement and law.'] },
          { title: 'Customer data', paragraphs: ['Personal information is stored and processed in accordance with applicable local law and will not be sold to third parties. You agree that important notices may be sent to your recorded email address and may opt out where available.'] },
          { title: 'Indemnification', paragraphs: ['Each party agrees to defend, indemnify and hold the other party and its personnel harmless from claims, damages, obligations, losses, liabilities, costs and expenses arising from use of the service or breach of these terms. The indemnifying party controls the defense with reasonable cooperation from the other party.'] },
          { title: 'Liability', paragraphs: ['Shoply and its suppliers are not liable for indirect or consequential losses caused by use or inability to use Shoply, including loss of profit, revenue, business, goodwill, opportunity, savings, reputation, use or data, to the extent permitted by law. Some jurisdictions may not permit all limitations.'] },
          { title: 'Severability and modifications', paragraphs: ['If any provision is invalid or unenforceable, it is severed to that extent without affecting the remainder. Shoply may update these terms by publishing revisions on its website. Continued use after revisions take effect constitutes acceptance.'] },
          { title: 'Governing law', paragraphs: ['These terms are governed by and construed under the laws of China, without regard to conflict-of-law provisions.'] }
        ]
      }
    },
    pricing: { title: 'Plans that grow with your business', description: 'Prices, billing periods and included capabilities come directly from the active APay subscription catalog.', included: 'Included features', action: 'Choose this plan', emptyTitle: 'No subscription plans are available', emptyDescription: 'The Shoply team is preparing the current plan catalog. Contact us for a tailored quote.', contact: 'Contact sales', cycle: { month: 'month', year: 'year', lifetime: 'lifetime' }, seoTitle: 'Shoply Subscription Pricing', seoDescription: 'Compare active Shoply subscription plans from the APay product and billing catalog.' }
  },
}
