CREATE TABLE IF NOT EXISTS `ext_apps_catalog` (
  `id` varchar(36) PRIMARY KEY NOT NULL,
  `name` varchar(160) NOT NULL,
  `types` varchar(16) NOT NULL,
  `slug` varchar(160) NOT NULL UNIQUE,
  `image_url` text,
  `subtitle` varchar(500) NOT NULL DEFAULT '',
  `price_amount` bigint NOT NULL DEFAULT 0,
  `content` longtext NOT NULL,
  `downs` int NOT NULL DEFAULT 0,
  `status` smallint NOT NULL DEFAULT 10,
  `unique_name` varchar(190) NOT NULL UNIQUE,
  `package_url` text NOT NULL,
  `version` varchar(80) NOT NULL,
  `installs_json` longtext NOT NULL,
  `settings_json` text NOT NULL,
  `seo_title` varchar(300) NOT NULL DEFAULT '',
  `seo_keywords` varchar(500) NOT NULL DEFAULT '',
  `seo_description` varchar(1000) NOT NULL DEFAULT '',
  `created_at` varchar(30) NOT NULL,
  `updated_at` varchar(30) NOT NULL,
  CHECK (`types` IN ('theme', 'plugin')),
  CHECK (`status` IN (10, 20)),
  CHECK (`price_amount` >= 0),
  CHECK (`downs` >= 0),
  INDEX `ext_apps_catalog_status_updated_idx` (`status`, `updated_at`)
);
