// Auto-generated by scripts/generate-extension-build.mjs. Do not edit manually.
import type { EventHandler } from 'h3'
import handler0 from '../../app/extensions/apps/api/admin/catalog/list.get'
import handler1 from '../../app/extensions/apps/api/admin/catalog/detail.get'
import handler2 from '../../app/extensions/apps/api/admin/catalog/create.post'
import handler3 from '../../app/extensions/apps/api/admin/catalog/update.patch'
import handler4 from '../../app/extensions/apps/api/admin/catalog/delete.delete'
import handler5 from '../../app/extensions/example-tools/api/admin/status.get'
import handler6 from '../../app/extensions/example-tools/api/user/profile.get'
import handler7 from '../../app/extensions/theme/api/admin/catalog/list.get'
import handler8 from '../../app/extensions/theme/api/admin/catalog/detail.get'
import handler9 from '../../app/extensions/theme/api/admin/catalog/create.post'
import handler10 from '../../app/extensions/theme/api/admin/catalog/update.patch'
import handler11 from '../../app/extensions/theme/api/admin/catalog/delete.delete'

export const extensionManifests = [
  {
    "schemaVersion": 1,
    "id": "apps",
    "name": "App Catalog",
    "description": "Manage downloadable app and plugin packages published in the Shoply marketplace.",
    "version": "1.0.0",
    "defaultEnabled": false,
    "capabilities": [
      {
        "key": "catalog",
        "label": "App Catalog",
        "labelZh": "应用管理",
        "editable": true
      }
    ],
    "adminPages": [
      {
        "key": "catalog",
        "title": "Apps",
        "titleZh": "应用管理",
        "description": "Manage app packages, releases, and marketplace metadata.",
        "descriptionZh": "管理应用包、版本和市场元数据。",
        "component": "catalog.vue",
        "capability": "catalog",
        "icon": "ph:app-window",
        "order": 40
      }
    ],
    "userPages": [],
    "adminApis": [
      {
        "method": "get",
        "path": "catalog/list",
        "capability": "catalog"
      },
      {
        "method": "get",
        "path": "catalog/detail",
        "capability": "catalog"
      },
      {
        "method": "post",
        "path": "catalog/create",
        "capability": "catalog"
      },
      {
        "method": "patch",
        "path": "catalog/update",
        "capability": "catalog"
      },
      {
        "method": "delete",
        "path": "catalog/delete",
        "capability": "catalog"
      }
    ],
    "userApis": [],
    "database": {
      "migrations": [
        {
          "id": "0001-create-catalog",
          "checksums": {
            "sqlite": "5e824801389f994559c3cf1bfc702b9231f6e25bba6af9fe04aa23437715a05b",
            "postgresql": "3426b0981dcde689766ac5253e3e060bafe617745067bf97a41b125679a40732",
            "mysql": "bfdd242d1d076dc55812f99a477b19a73f40049422f00ce95e3d7dd82f5783c4"
          }
        }
      ]
    }
  },
  {
    "schemaVersion": 1,
    "id": "example-tools",
    "name": "Example Tools",
    "description": "A safe reference extension demonstrating APay pages, APIs, permissions, and enablement.",
    "version": "1.0.0",
    "defaultEnabled": false,
    "capabilities": [
      {
        "key": "overview",
        "label": "Example Tools",
        "labelZh": "示例工具",
        "editable": false
      }
    ],
    "adminPages": [
      {
        "key": "overview",
        "title": "Example Tools",
        "titleZh": "示例工具",
        "description": "Inspect the extension host and admin API.",
        "descriptionZh": "检查扩展宿主与后台 API。",
        "component": "overview.vue",
        "capability": "overview",
        "icon": "ph:puzzle-piece",
        "order": 10
      }
    ],
    "userPages": [
      {
        "key": "overview",
        "title": "Example Tools",
        "titleZh": "示例工具",
        "component": "overview.vue"
      }
    ],
    "adminApis": [
      {
        "method": "get",
        "path": "overview/status",
        "capability": "overview"
      }
    ],
    "userApis": [
      {
        "method": "get",
        "path": "profile"
      }
    ],
    "database": {
      "migrations": [
        {
          "id": "0001-create-records",
          "checksums": {
            "sqlite": "64cf3362b5efba0330b8fb65a0443f9251f28e576195fc53842dcb5f2a6598ab",
            "postgresql": "be0bb95ad1b6c3769e5df57a20ac2ca5f1c07a3827b08efbd95514636b6d0efb",
            "mysql": "6f3b239bbbec0ac039aa12c06ca5c2df93d75ce135bf8b0aa1cdd89b4d2c7c13"
          }
        }
      ]
    }
  },
  {
    "schemaVersion": 1,
    "id": "theme",
    "name": "Theme Catalog",
    "description": "Manage downloadable storefront theme packages published in the Shoply marketplace.",
    "version": "1.0.0",
    "defaultEnabled": false,
    "capabilities": [
      {
        "key": "catalog",
        "label": "Theme Catalog",
        "labelZh": "主题管理",
        "editable": true
      }
    ],
    "adminPages": [
      {
        "key": "catalog",
        "title": "Themes",
        "titleZh": "主题管理",
        "description": "Manage storefront theme packages, demos, and marketplace metadata.",
        "descriptionZh": "管理店铺主题包、演示地址和市场元数据。",
        "component": "catalog.vue",
        "capability": "catalog",
        "icon": "ph:paint-brush-broad",
        "order": 41
      }
    ],
    "userPages": [],
    "adminApis": [
      {
        "method": "get",
        "path": "catalog/list",
        "capability": "catalog"
      },
      {
        "method": "get",
        "path": "catalog/detail",
        "capability": "catalog"
      },
      {
        "method": "post",
        "path": "catalog/create",
        "capability": "catalog"
      },
      {
        "method": "patch",
        "path": "catalog/update",
        "capability": "catalog"
      },
      {
        "method": "delete",
        "path": "catalog/delete",
        "capability": "catalog"
      }
    ],
    "userApis": [],
    "database": {
      "migrations": [
        {
          "id": "0001-create-catalog",
          "checksums": {
            "sqlite": "bd4f9ed1c276bf44907beb6c4aba8b93c2f8bf794a08a680cf64c27212141662",
            "postgresql": "a0387d5ccaccf751844950f198586d6743b8f5f11fcb706c1658632ea66ffdfd",
            "mysql": "266f096d48f9b4ffe3bb369df005bc447344892d38a9d9ceca191d8d6cb7498c"
          }
        }
      ]
    }
  }
] as const

export interface ExtensionApiRoute {
  extension: string
  method: string
  path: string
  capability?: string
  handler: EventHandler
}

export const extensionAdminApiRoutes: ExtensionApiRoute[] = [
  { extension: "apps", method: "GET", path: "catalog/list", capability: "catalog", handler: handler0 },
  { extension: "apps", method: "GET", path: "catalog/detail", capability: "catalog", handler: handler1 },
  { extension: "apps", method: "POST", path: "catalog/create", capability: "catalog", handler: handler2 },
  { extension: "apps", method: "PATCH", path: "catalog/update", capability: "catalog", handler: handler3 },
  { extension: "apps", method: "DELETE", path: "catalog/delete", capability: "catalog", handler: handler4 },
  { extension: "example-tools", method: "GET", path: "overview/status", capability: "overview", handler: handler5 },
  { extension: "theme", method: "GET", path: "catalog/list", capability: "catalog", handler: handler7 },
  { extension: "theme", method: "GET", path: "catalog/detail", capability: "catalog", handler: handler8 },
  { extension: "theme", method: "POST", path: "catalog/create", capability: "catalog", handler: handler9 },
  { extension: "theme", method: "PATCH", path: "catalog/update", capability: "catalog", handler: handler10 },
  { extension: "theme", method: "DELETE", path: "catalog/delete", capability: "catalog", handler: handler11 },
]

export const extensionUserApiRoutes: ExtensionApiRoute[] = [
  { extension: "example-tools", method: "GET", path: "profile", handler: handler6 },
]

export type ExtensionDatabaseDialect = 'sqlite' | 'postgresql' | 'mysql'

export interface ExtensionDatabaseMigration {
  extension: string
  id: string
  dialects: Record<ExtensionDatabaseDialect, { file: string, checksum: string, statements: string[] }>
}

export const extensionDatabaseMigrations: ExtensionDatabaseMigration[] = [
  {
    "extension": "apps",
    "id": "0001-create-catalog",
    "dialects": {
      "sqlite": {
        "file": "sqlite/0001-create-catalog.sql",
        "checksum": "5e824801389f994559c3cf1bfc702b9231f6e25bba6af9fe04aa23437715a05b",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_apps_catalog` (\n  `id` text PRIMARY KEY NOT NULL,\n  `name` text NOT NULL,\n  `types` text NOT NULL,\n  `slug` text NOT NULL UNIQUE,\n  `image_url` text,\n  `subtitle` text NOT NULL DEFAULT '',\n  `price_amount` integer NOT NULL DEFAULT 0,\n  `content` text NOT NULL DEFAULT '',\n  `downs` integer NOT NULL DEFAULT 0,\n  `status` integer NOT NULL DEFAULT 10,\n  `unique_name` text NOT NULL UNIQUE,\n  `package_url` text NOT NULL,\n  `version` text NOT NULL,\n  `installs_json` text NOT NULL DEFAULT '[]',\n  `settings_json` text NOT NULL DEFAULT '{}',\n  `seo_title` text NOT NULL DEFAULT '',\n  `seo_keywords` text NOT NULL DEFAULT '',\n  `seo_description` text NOT NULL DEFAULT '',\n  `created_at` text NOT NULL,\n  `updated_at` text NOT NULL,\n  CHECK (`types` IN ('theme', 'plugin')),\n  CHECK (`status` IN (10, 20)),\n  CHECK (`price_amount` >= 0),\n  CHECK (`downs` >= 0)\n);",
          "CREATE INDEX IF NOT EXISTS `ext_apps_catalog_status_updated_idx` ON `ext_apps_catalog` (`status`, `updated_at`);"
        ]
      },
      "postgresql": {
        "file": "postgresql/0001-create-catalog.sql",
        "checksum": "3426b0981dcde689766ac5253e3e060bafe617745067bf97a41b125679a40732",
        "statements": [
          "CREATE TABLE IF NOT EXISTS \"ext_apps_catalog\" (\n  \"id\" text PRIMARY KEY NOT NULL,\n  \"name\" text NOT NULL,\n  \"types\" text NOT NULL,\n  \"slug\" text NOT NULL UNIQUE,\n  \"image_url\" text,\n  \"subtitle\" text NOT NULL DEFAULT '',\n  \"price_amount\" bigint NOT NULL DEFAULT 0,\n  \"content\" text NOT NULL DEFAULT '',\n  \"downs\" integer NOT NULL DEFAULT 0,\n  \"status\" smallint NOT NULL DEFAULT 10,\n  \"unique_name\" text NOT NULL UNIQUE,\n  \"package_url\" text NOT NULL,\n  \"version\" text NOT NULL,\n  \"installs_json\" text NOT NULL DEFAULT '[]',\n  \"settings_json\" text NOT NULL DEFAULT '{}',\n  \"seo_title\" text NOT NULL DEFAULT '',\n  \"seo_keywords\" text NOT NULL DEFAULT '',\n  \"seo_description\" text NOT NULL DEFAULT '',\n  \"created_at\" text NOT NULL,\n  \"updated_at\" text NOT NULL,\n  CHECK (\"types\" IN ('theme', 'plugin')),\n  CHECK (\"status\" IN (10, 20)),\n  CHECK (\"price_amount\" >= 0),\n  CHECK (\"downs\" >= 0)\n);",
          "CREATE INDEX IF NOT EXISTS \"ext_apps_catalog_status_updated_idx\" ON \"ext_apps_catalog\" (\"status\", \"updated_at\");"
        ]
      },
      "mysql": {
        "file": "mysql/0001-create-catalog.sql",
        "checksum": "bfdd242d1d076dc55812f99a477b19a73f40049422f00ce95e3d7dd82f5783c4",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_apps_catalog` (\n  `id` varchar(36) PRIMARY KEY NOT NULL,\n  `name` varchar(160) NOT NULL,\n  `types` varchar(16) NOT NULL,\n  `slug` varchar(160) NOT NULL UNIQUE,\n  `image_url` text,\n  `subtitle` varchar(500) NOT NULL DEFAULT '',\n  `price_amount` bigint NOT NULL DEFAULT 0,\n  `content` longtext NOT NULL,\n  `downs` int NOT NULL DEFAULT 0,\n  `status` smallint NOT NULL DEFAULT 10,\n  `unique_name` varchar(190) NOT NULL UNIQUE,\n  `package_url` text NOT NULL,\n  `version` varchar(80) NOT NULL,\n  `installs_json` longtext NOT NULL,\n  `settings_json` text NOT NULL,\n  `seo_title` varchar(300) NOT NULL DEFAULT '',\n  `seo_keywords` varchar(500) NOT NULL DEFAULT '',\n  `seo_description` varchar(1000) NOT NULL DEFAULT '',\n  `created_at` varchar(30) NOT NULL,\n  `updated_at` varchar(30) NOT NULL,\n  CHECK (`types` IN ('theme', 'plugin')),\n  CHECK (`status` IN (10, 20)),\n  CHECK (`price_amount` >= 0),\n  CHECK (`downs` >= 0),\n  INDEX `ext_apps_catalog_status_updated_idx` (`status`, `updated_at`)\n);"
        ]
      }
    }
  },
  {
    "extension": "example-tools",
    "id": "0001-create-records",
    "dialects": {
      "sqlite": {
        "file": "sqlite/0001-create-records.sql",
        "checksum": "64cf3362b5efba0330b8fb65a0443f9251f28e576195fc53842dcb5f2a6598ab",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_example_tools_records` (\n  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n  `value` text NOT NULL,\n  `created_at` integer DEFAULT (unixepoch()) NOT NULL\n);"
        ]
      },
      "postgresql": {
        "file": "postgresql/0001-create-records.sql",
        "checksum": "be0bb95ad1b6c3769e5df57a20ac2ca5f1c07a3827b08efbd95514636b6d0efb",
        "statements": [
          "CREATE TABLE IF NOT EXISTS \"ext_example_tools_records\" (\n  \"id\" serial PRIMARY KEY,\n  \"value\" text NOT NULL,\n  \"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);"
        ]
      },
      "mysql": {
        "file": "mysql/0001-create-records.sql",
        "checksum": "6f3b239bbbec0ac039aa12c06ca5c2df93d75ce135bf8b0aa1cdd89b4d2c7c13",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_example_tools_records` (\n  `id` int AUTO_INCREMENT PRIMARY KEY,\n  `value` text NOT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL\n);"
        ]
      }
    }
  },
  {
    "extension": "theme",
    "id": "0001-create-catalog",
    "dialects": {
      "sqlite": {
        "file": "sqlite/0001-create-catalog.sql",
        "checksum": "bd4f9ed1c276bf44907beb6c4aba8b93c2f8bf794a08a680cf64c27212141662",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_theme_catalog` (\n  `id` text PRIMARY KEY NOT NULL,\n  `name` text NOT NULL,\n  `category` text NOT NULL DEFAULT '',\n  `slug` text NOT NULL UNIQUE,\n  `image_url` text,\n  `subtitle` text NOT NULL DEFAULT '',\n  `price_amount` integer NOT NULL DEFAULT 0,\n  `content` text NOT NULL DEFAULT '',\n  `downs` integer NOT NULL DEFAULT 0,\n  `status` integer NOT NULL DEFAULT 10,\n  `unique_name` text NOT NULL UNIQUE,\n  `package_url` text,\n  `demo_url` text,\n  `settings_json` text NOT NULL DEFAULT '{}',\n  `seo_title` text NOT NULL DEFAULT '',\n  `seo_keywords` text NOT NULL DEFAULT '',\n  `seo_description` text NOT NULL DEFAULT '',\n  `created_at` text NOT NULL,\n  `updated_at` text NOT NULL,\n  CHECK (`status` IN (10, 20)),\n  CHECK (`price_amount` >= 0),\n  CHECK (`downs` >= 0)\n);",
          "CREATE INDEX IF NOT EXISTS `ext_theme_catalog_status_updated_idx` ON `ext_theme_catalog` (`status`, `updated_at`);"
        ]
      },
      "postgresql": {
        "file": "postgresql/0001-create-catalog.sql",
        "checksum": "a0387d5ccaccf751844950f198586d6743b8f5f11fcb706c1658632ea66ffdfd",
        "statements": [
          "CREATE TABLE IF NOT EXISTS \"ext_theme_catalog\" (\n  \"id\" text PRIMARY KEY NOT NULL,\n  \"name\" text NOT NULL,\n  \"category\" text NOT NULL DEFAULT '',\n  \"slug\" text NOT NULL UNIQUE,\n  \"image_url\" text,\n  \"subtitle\" text NOT NULL DEFAULT '',\n  \"price_amount\" bigint NOT NULL DEFAULT 0,\n  \"content\" text NOT NULL DEFAULT '',\n  \"downs\" integer NOT NULL DEFAULT 0,\n  \"status\" smallint NOT NULL DEFAULT 10,\n  \"unique_name\" text NOT NULL UNIQUE,\n  \"package_url\" text,\n  \"demo_url\" text,\n  \"settings_json\" text NOT NULL DEFAULT '{}',\n  \"seo_title\" text NOT NULL DEFAULT '',\n  \"seo_keywords\" text NOT NULL DEFAULT '',\n  \"seo_description\" text NOT NULL DEFAULT '',\n  \"created_at\" text NOT NULL,\n  \"updated_at\" text NOT NULL,\n  CHECK (\"status\" IN (10, 20)),\n  CHECK (\"price_amount\" >= 0),\n  CHECK (\"downs\" >= 0)\n);",
          "CREATE INDEX IF NOT EXISTS \"ext_theme_catalog_status_updated_idx\" ON \"ext_theme_catalog\" (\"status\", \"updated_at\");"
        ]
      },
      "mysql": {
        "file": "mysql/0001-create-catalog.sql",
        "checksum": "266f096d48f9b4ffe3bb369df005bc447344892d38a9d9ceca191d8d6cb7498c",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_theme_catalog` (\n  `id` varchar(36) PRIMARY KEY NOT NULL,\n  `name` varchar(160) NOT NULL,\n  `category` varchar(120) NOT NULL DEFAULT '',\n  `slug` varchar(160) NOT NULL UNIQUE,\n  `image_url` text,\n  `subtitle` varchar(500) NOT NULL DEFAULT '',\n  `price_amount` bigint NOT NULL DEFAULT 0,\n  `content` longtext NOT NULL,\n  `downs` int NOT NULL DEFAULT 0,\n  `status` smallint NOT NULL DEFAULT 10,\n  `unique_name` varchar(190) NOT NULL UNIQUE,\n  `package_url` text,\n  `demo_url` text,\n  `settings_json` text NOT NULL,\n  `seo_title` varchar(300) NOT NULL DEFAULT '',\n  `seo_keywords` varchar(500) NOT NULL DEFAULT '',\n  `seo_description` varchar(1000) NOT NULL DEFAULT '',\n  `created_at` varchar(30) NOT NULL,\n  `updated_at` varchar(30) NOT NULL,\n  CHECK (`status` IN (10, 20)),\n  CHECK (`price_amount` >= 0),\n  CHECK (`downs` >= 0),\n  INDEX `ext_theme_catalog_status_updated_idx` (`status`, `updated_at`)\n);"
        ]
      }
    }
  }
]
