// Auto-generated by scripts/generate-extension-build.mjs. Do not edit manually.
import type { EventHandler } from 'h3'
import handler0 from '../../app/extensions/example-tools/api/admin/status.get'
import handler1 from '../../app/extensions/example-tools/api/user/profile.get'

export const extensionManifests = [
  {
    "schemaVersion": 1,
    "id": "example-tools",
    "name": "Example Tools",
    "description": "A safe reference extension demonstrating APay pages, APIs, permissions, and enablement.",
    "version": "1.0.0",
    "defaultEnabled": false,
    "capabilities": [
      {
        "key": "overview",
        "label": "Example Tools",
        "labelZh": "示例工具",
        "editable": false
      }
    ],
    "adminPages": [
      {
        "key": "overview",
        "title": "Example Tools",
        "titleZh": "示例工具",
        "description": "Inspect the extension host and admin API.",
        "descriptionZh": "检查扩展宿主与后台 API。",
        "component": "overview.vue",
        "capability": "overview",
        "icon": "ph:puzzle-piece",
        "order": 10
      }
    ],
    "userPages": [
      {
        "key": "overview",
        "title": "Example Tools",
        "titleZh": "示例工具",
        "component": "overview.vue"
      }
    ],
    "adminApis": [
      {
        "method": "get",
        "path": "overview/status",
        "capability": "overview"
      }
    ],
    "userApis": [
      {
        "method": "get",
        "path": "profile"
      }
    ],
    "database": {
      "migrations": [
        {
          "id": "0001-create-records",
          "checksums": {
            "sqlite": "64cf3362b5efba0330b8fb65a0443f9251f28e576195fc53842dcb5f2a6598ab",
            "postgresql": "be0bb95ad1b6c3769e5df57a20ac2ca5f1c07a3827b08efbd95514636b6d0efb",
            "mysql": "6f3b239bbbec0ac039aa12c06ca5c2df93d75ce135bf8b0aa1cdd89b4d2c7c13"
          }
        }
      ]
    }
  }
] as const

export interface ExtensionApiRoute {
  extension: string
  method: string
  path: string
  capability?: string
  handler: EventHandler
}

export const extensionAdminApiRoutes: ExtensionApiRoute[] = [
  { extension: "example-tools", method: "GET", path: "overview/status", capability: "overview", handler: handler0 },
]

export const extensionUserApiRoutes: ExtensionApiRoute[] = [
  { extension: "example-tools", method: "GET", path: "profile", handler: handler1 },
]

export type ExtensionDatabaseDialect = 'sqlite' | 'postgresql' | 'mysql'

export interface ExtensionDatabaseMigration {
  extension: string
  id: string
  dialects: Record<ExtensionDatabaseDialect, { file: string, checksum: string, statements: string[] }>
}

export const extensionDatabaseMigrations: ExtensionDatabaseMigration[] = [
  {
    "extension": "example-tools",
    "id": "0001-create-records",
    "dialects": {
      "sqlite": {
        "file": "sqlite/0001-create-records.sql",
        "checksum": "64cf3362b5efba0330b8fb65a0443f9251f28e576195fc53842dcb5f2a6598ab",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_example_tools_records` (\n  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n  `value` text NOT NULL,\n  `created_at` integer DEFAULT (unixepoch()) NOT NULL\n);"
        ]
      },
      "postgresql": {
        "file": "postgresql/0001-create-records.sql",
        "checksum": "be0bb95ad1b6c3769e5df57a20ac2ca5f1c07a3827b08efbd95514636b6d0efb",
        "statements": [
          "CREATE TABLE IF NOT EXISTS \"ext_example_tools_records\" (\n  \"id\" serial PRIMARY KEY,\n  \"value\" text NOT NULL,\n  \"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);"
        ]
      },
      "mysql": {
        "file": "mysql/0001-create-records.sql",
        "checksum": "6f3b239bbbec0ac039aa12c06ca5c2df93d75ce135bf8b0aa1cdd89b4d2c7c13",
        "statements": [
          "CREATE TABLE IF NOT EXISTS `ext_example_tools_records` (\n  `id` int AUTO_INCREMENT PRIMARY KEY,\n  `value` text NOT NULL,\n  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL\n);"
        ]
      }
    }
  }
]
