// Auto-generated by scripts/generate-extension-build.mjs. Do not edit manually.
export const extensionDatabaseRequirements: Record<string, Record<'sqlite' | 'postgresql' | 'mysql', Record<string, string>>> = {
  "apps": {
    "sqlite": {
      "0001-create-catalog": "5e824801389f994559c3cf1bfc702b9231f6e25bba6af9fe04aa23437715a05b"
    },
    "postgresql": {
      "0001-create-catalog": "3426b0981dcde689766ac5253e3e060bafe617745067bf97a41b125679a40732"
    },
    "mysql": {
      "0001-create-catalog": "bfdd242d1d076dc55812f99a477b19a73f40049422f00ce95e3d7dd82f5783c4"
    }
  },
  "example-tools": {
    "sqlite": {
      "0001-create-records": "64cf3362b5efba0330b8fb65a0443f9251f28e576195fc53842dcb5f2a6598ab"
    },
    "postgresql": {
      "0001-create-records": "be0bb95ad1b6c3769e5df57a20ac2ca5f1c07a3827b08efbd95514636b6d0efb"
    },
    "mysql": {
      "0001-create-records": "6f3b239bbbec0ac039aa12c06ca5c2df93d75ce135bf8b0aa1cdd89b4d2c7c13"
    }
  },
  "theme": {
    "sqlite": {
      "0001-create-catalog": "bd4f9ed1c276bf44907beb6c4aba8b93c2f8bf794a08a680cf64c27212141662"
    },
    "postgresql": {
      "0001-create-catalog": "a0387d5ccaccf751844950f198586d6743b8f5f11fcb706c1658632ea66ffdfd"
    },
    "mysql": {
      "0001-create-catalog": "266f096d48f9b4ffe3bb369df005bc447344892d38a9d9ceca191d8d6cb7498c"
    }
  }
}
