// Auto-generated by scripts/generate-extension-build.mjs. Do not edit manually.
export const extensionDatabaseRequirements: Record<string, Record<'sqlite' | 'postgresql' | 'mysql', Record<string, string>>> = {
  "example-tools": {
    "sqlite": {
      "0001-create-records": "64cf3362b5efba0330b8fb65a0443f9251f28e576195fc53842dcb5f2a6598ab"
    },
    "postgresql": {
      "0001-create-records": "be0bb95ad1b6c3769e5df57a20ac2ca5f1c07a3827b08efbd95514636b6d0efb"
    },
    "mysql": {
      "0001-create-records": "6f3b239bbbec0ac039aa12c06ca5c2df93d75ce135bf8b0aa1cdd89b4d2c7c13"
    }
  }
}
